version: '3'
services:
  web1:
    build:
      context: ./dubbo-provider
      dockerfile: DockerFile
    ports:
      - 10102:10102
  web2:
    build:
      context: ./dubbo-provider
      dockerfile: DockerFile
    ports:
      - 10103:10102
