version: '3'
services:
  rabbitmq0:
     container_name: rabbitmq0
     image: rabbitmq:management
     ports:
     - "5671:5672"
     - "15671:15672"
     restart: always

  app:
    restart: always
    build: .
    working_dir: /
    volumes:
      - .:/
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    depends_on:
      - rabbitmq0
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker